### ISSUE TITLE
ready event isn't emitted

### ISSUE THREAD

**Issue by parapente** [mayasabha/ckeditor4-vue3#1]
I'm upgrading my application from vue2 to vue3 trying to modify as little as possible the original code that is already working. I used ckeditor4-vue3 instead of the original ckeditor4-vue component but it seems that the ready event is never fired, just update:modelValue. As a result, a callback function that I was using to setup the application and should be called only once is never used.

For now I had to resort to running the callback on update:modelValue and use a flag to configure the app only once.

**Comment by apoorvpal01** [comment]
@parapente Please check with `v0.0.4` if the issue is fixed.
