### ISSUE TITLE
copy event

### ISSUE THREAD

**Issue by edusouza96** [mayasabha/ckeditor4-vue3#15]
Is there any possibility of listening to the copy event, as we do with the paste event

**Comment by apoorvpal01** [comment]
You can use event listeners for events that CKEditor4 natively supports, but I believe there is no copy event emitted from CKEditor4. Available events are listed on their official website: https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#event-activeEnterModeChange

The example below shows how you can listen to the `paste` event by accessing the CKEditor instance within the component. For copy, you could potentially create a workaround by interacting with the browser clipboard API directly, but CKEditor4 does not have any such functionality currently.

```vue
<script setup lang="ts">
  import { useTemplateRef } from 'vue'
  import { component as CKEditor } from '@mayasabha/ckeditor4-vue3'
  const editor = useTemplateRef('editor')
  
  const onReady = (evt) => {
    const instance = editor.value.instance
    instance.on('paste', () => alert('Text pasted'))
  }
</script>

<template>
  <CKEditor ref="editor" v-on:ready="onReady" />
</template>
```
