### ISSUE TITLE
plugins

### ISSUE THREAD

**Issue by Djagannath** [mayasabha/ckeditor4-vue3#2]
Hello, how can I add plugins ?
My panel is soo poor

I need change colors, fonts, size
![panel](https://user-images.githubusercontent.com/22425146/182786134-29af112f-dcf4-4d5f-82b4-c9cc99a025c5.jpg)

**Comment by apoorvpal01** [comment]
@Djagannath the plugins functionality should be identical to how it's done in the CKEditor 4 VueJS 2 component. What method have you tried? You can also include a custom config.js after compiling a custom build by selecting packages from the CKEditor 4 website.

**Comment by Djagannath** [comment]
sorry for the delay.

To apply the parameters from config, I had to change the editorUrl to the local version 


  <ckeditor 
            type="classic"
            v-model="computedValue"
            :editorUrl="urlDevCkeditor"
            :config="config"
  />

and then it all appears

const config = {
  removePlugins: 'easyimage, cloudservices, exportpdf',
  uiColor: '#9AB8F3',
  toolbar: [
    {name: 'document', items: ['Source', '-', 'NewPage', 'Preview']},
    {name: 'clipboard', items: ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
    {name: 'editing', items: ['Find', 'Replace', '-', 'SelectAll', '-', 'Scayt']},
    {
      name: 'forms',
      items: ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField']
    },
    '/',
    {
      name: 'basicstyles',
      items: ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'CopyFormatting', 'RemoveFormat']
    },
    {
      name: 'paragraph',
      items: ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl', 'Language']
    },
    {name: 'links', items: ['Link', 'Unlink', 'Anchor']},
    {name: 'insert', items: ['Image', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe']},
    '/',
    {name: 'styles', items: ['Styles', 'Format', 'Font', 'FontSize']},
    {name: 'colors', items: ['TextColor', 'BGColor']},
    {name: 'tools', items: ['Maximize', 'ShowBlocks']},
    {name: 'about', items: ['About']}
  ],
  filebrowserBrowseUrl: route('cp.ckfinder_browser'),
  filebrowserImageBrowseUrl: route('cp.ckfinder_browser') + '?type=Images&token=123',
  filebrowserFlashBrowseUrl: route('cp.ckfinder_browser') + '?type=Flash&token=123',
  filebrowserUploadUrl: route('cp.ckfinder_connector') + '?command=QuickUpload&type=Files',
  filebrowserImageUploadUrl: route('cp.ckfinder_connector') + '?command=QuickUpload&type=Images',
  filebrowserFlashUploadUrl: route('cp.ckfinder_connector') + '?command=QuickUpload&type=Flash'
}
