### ISSUE TITLE
how to use delayIfDetached and delayIfDetached_callback in vue ckeditor?

### ISSUE THREAD

**Issue by nekooee** [mayasabha/ckeditor4-vue3#4]
I get the `Error code: editor-delayed-creation` message in the console. how do I use delayIfDetached and delayIfDetached_callback in the vue version of the editor??

**Comment by apoorvpal01** [comment]
@nekooee You should be able to pass the configuration object with those parameters as those are directly passed on to the CKEditor instance and not modified by the Vue wrapper.
